export { default as PostList } from './PostList';
export { default as CardServico } from './CardServico';
export { default as SlickServico } from './SlickServico';
export { default as SlickDepoimentos } from './SlickDepoimentos';
export { default as CardSobre } from './CardSobre';
export { default as CardDepoimento } from './CardDepoimento';
export { default as Footer } from './Footer';
export { default as SobreNos } from './SobreNos';
export { default as NavBar } from './NavBar';